#include<stdio.h>
#include<conio.h>
void main()
{
clrscr();
int ch;
printf("KBC");
printf("who is cm of MP\n");
printf("1)shivraj\n");
printf("2)namo\n");
printf("3)yogi\n");
printf("4)obama\n");
printf("enter your choice");
scanf("%d",&ch);
if(ch==1)
{
printf("your answer is correct\n");
printf("you won 1000 rs\n");
printf("who is PM of INDIA\n");
printf("1)namo\n");
printf("2)yogi\n");
printf("3)obama\n");
printf("4)shivraj\n");
printf("enetr your choice");
scanf("%d",&ch);
if(ch==1)
{
printf("your answer is correct\n");
printf("you won 5000 rs\n");
printf("who is father of nation\n");
printf("1)ravindranath\n");
printf("2)mahtma gandhi\n");
printf("3)narendra modi\n");
printf("4)bhagat shingh\n");
printf("enter your choice");
scanf("%d",&ch);
if(ch==2)
{
printf("your answer is correct\n");
printf("you won 10000 rs\n");
}
else
{
printf("your answer is wrong");
}
}
else
{
printf("your answer is wrong");
}
}
else
{
printf("your answer is wrong");
}
getch();
}
